using Gunock.DiagnosisReportGenerator.TestBase;

namespace Gunock.DiagnosisReportGenerator.EntityFrameworkCore.Tests.EntityFrameworkCore;

public abstract class DiagnosisReportGeneratorEntityFrameworkCoreTestBase : DiagnosisReportGeneratorTestBase<
    DiagnosisReportGeneratorEntityFrameworkCoreTestModule>
{
}