using ThomasKiljanczykDev.DiagnosisReportGenerator.TestBase;

namespace ThomasKiljanczykDev.DiagnosisReportGenerator.EntityFrameworkCore.Tests.EntityFrameworkCore;

public abstract class DiagnosisReportGeneratorEntityFrameworkCoreTestBase : DiagnosisReportGeneratorTestBase<
    DiagnosisReportGeneratorEntityFrameworkCoreTestModule>;